version: "3.8"

services:
  fastapi:
    image: fraud-detection-app:latest
    container_name: fastapi-app
    ports:
      - "8000:8000"
    command: "uvicorn api.main:app --host 0.0.0.0 --port 8000"
    restart: always
    volumes:
      - .:/app

  streamlit:
    image: fraud-detection-app:latest
    container_name: streamlit-app
    ports:
      - "8501:8501"
    command: "streamlit run app.py --server.port 8501 --server.address 0.0.0.0"
    restart: always
    volumes:
      - .:/app
    depends_on:
      - fastapi
